### ISSUE TITLE
Комментарии к первоначальной заявке - [работа прислана до дедлайна]

### ISSUE THREAD

**Issue by aakuptsov** [ivanbarbashin/Final_graduation_work_repo#1]
1. Заявка впечатляет степенью проработанности, такое встречается нечасто. Но нужно заполнить поля и 23:59. Содержание для раздела "Образ продукта" можно скопировать из "Функциональных требований". 

2. >>Расписание тренировок, игр, турниров

Как это расписание будет попадать на сайт? Парситься где-то и подгружаться или заводиться вручную?

3. Укажи, пожалуйста, какая будет БД.

**Comment by letsssgooo** [comment]
Поля на 23:59 заполнил.
Расписание будет заводится вручную. Тренер собственноручно будет создавать график тренировок, игр и турниров, который будет отображаться у подопечных.
Базу данных указал в инструментах разработки.

**Comment by aakuptsov** [comment]
1. "окно статистики по тренировкам" и "рейтинг каждого упражнения" - тут нет глаголов или отглагольных существительных, поэтому непонятно, что, например, будет происходить с рейтингом. Прошу только не писать "просмотр" или подобное, потому что это действие, не требующее каких-то активных "движений" со стороны пользователя.

**Comment by letsssgooo** [comment]
Окно статистики - страница на сайте для просмотра количества тренировок за выбранный промежуток времени(неделя, месяц, год), среднее время тренировки, процентное соотношение групп мышц, которые тренировал спортсмен.
Рейтинг упражнения - 5-и бальная оценка эффективности упражнения путём вычисления среднего арифметического среди всех оценок пользователей. Будет отображаться под каждым упражнением.

**Comment by aakuptsov** [comment]
ЗАЧЁТ
